name: notably
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Dependencias existentes
  supabase_flutter: ^2.10.0
  flutter_riverpod: ^2.0.0
  
  # Rich Text Editor - NUEVAS
  flutter_quill: ^11.4.2
  flutter_quill_extensions: ^11.0.0
  
  # Date formatting
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  
  # Additional dependencies for Notion-like features
  uuid: ^4.5.1
  reorderables: ^0.6.0
  flutter_staggered_animations: ^1.1.1
  animations: ^2.0.11
  flutter_slidable: ^4.0.1
  cached_network_image: ^3.4.1
  path_provider: ^2.1.4
  sqflite: ^2.4.1
  connectivity_plus: ^6.1.0
  equatable: ^2.0.5
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter_mentions: ^2.0.1
  flutter_typeahead: ^5.2.0
  
  # Real-time Collaboration Dependencies
  web_socket_channel: ^3.0.1
  socket_io_client: ^3.1.2
  flutter_webrtc: ^1.1.0
  
  # Export/Import Dependencies
  pdf: ^3.11.1
  printing: ^5.13.4
  file_picker: ^10.3.2
  share_plus: ^11.1.0
  
  # Authentication Dependencies
  google_sign_in: ^6.2.1
  
  # Performance & State
  collection: ^1.18.0
  rxdart: ^0.28.0
  
  # Professional UI Design Libraries (Notion-like)
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  lottie: ^3.1.3
  flutter_svg: ^2.0.10
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  smooth_page_indicator: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true